In [1]:
import pandas as pd
df = pd.read_csv('antibiotic_resistance_dataset.csv') 
df.head()

   age gender specimen       organism     antibiotic  resistant
0   52      M    urine        E. coli  Ciprofloxacin          0
1   15      F   sputum  K. pneumoniae    Ceftriaxone          1
2   72      M    urine  K. pneumoniae      Meropenem          0
3   61      F   sputum  P. aeruginosa    Ceftriaxone          1
4   21      F   sputum      S. aureus    Ceftriaxone          0

In [2]:
X = df.drop('resistant', axis=1)   
y = df['resistant']

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)
print("Training set size:", len(X_train))
print("Test set size:", len(X_test))

Training set size: 375
Test set size: 125

In [7]:
from sklearn.preprocessing import LabelEncoder
encoders = {}
for col in ['gender', 'specimen', 'organism', 'antibiotic']:
    le = LabelEncoder()
    X_train[col] = le.fit_transform(X_train[col])
    X_test[col] = le.transform(X_test[col])    
    encoders[col] = le

In [8]:
X_train.head()

     age  gender  specimen  organism  antibiotic
227   86       1         0         0           2
417   13       1         1         0           0
203   81       1         1         0           3
126   88       0         1         3           1
329   17       1         1         3           3

In [9]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [10]:
y_pred = model.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test, y_pred)
print(f"Accuracy: {acc:.2f} ({acc*100:.1f}%)")

Accuracy: 0.66 (66.4%)

In [12]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[64 20]
 [22 19]]

In [13]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred, target_names=['Sensitive', 'Resistant']))

              precision    recall  f1-score   support

   Sensitive       0.74      0.76      0.75        84
   Resistant       0.49      0.46      0.47        41

    accuracy                           0.66       125
   macro avg       0.62      0.61      0.61       125
weighted avg       0.66      0.66      0.66       125

In [14]:
import joblib
joblib.dump(model, 'prediction_model.pkl')
joblib.dump(encoders, 'feature_encoders.pkl')
print("prediction_model and feature_encoders saved.")

prediction_model and feature_encoders saved.